
/**
 *
 * @author flor
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class cajero extends javax.swing.JFrame {

    String us="root";
    String pasword="123flor";  
    String url = "jdbc:mysql://localhost:3306/sistemaventas?serverTimezone=UTC";
    Statement s;
    Connection conexion;
    PreparedStatement ps;
    static DefaultTableModel tablaventa = new DefaultTableModel();// tabla ventas
    static DefaultTableModel tablaprod = new DefaultTableModel();// tabla de produtos

    public cajero() {
      initComponents();
        tablaventa = (DefaultTableModel)jTable1.getModel();
        tablaprod = (DefaultTableModel)jTable1.getModel();

     setLocationRelativeTo(null);
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jButton1busca = new javax.swing.JButton();
        jLabel3nomprod = new javax.swing.JLabel();
        buscarprod = new javax.swing.JTextField();
        jButton2cancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        datosventa = new javax.swing.JLabel();
        jLabel5cliente = new javax.swing.JLabel();
        clientevendido = new javax.swing.JTextField();
        jLabel6fecha = new javax.swing.JLabel();
        fechavendido = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7total = new javax.swing.JLabel();
        jLabel8preciounitariop = new javax.swing.JLabel();
        jLabel9cantidad = new javax.swing.JLabel();
        preciounitario = new javax.swing.JTextField();
        totalvendido = new javax.swing.JTextField();
        btnnueva = new javax.swing.JButton();
        btngenerarventa = new javax.swing.JButton();
        btnrecibo = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        cantidadvendido = new javax.swing.JSpinner();
        prodvendido = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1cajero = new javax.swing.JLabel();
        jButton8salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));

        jButton1busca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/busca.jpg"))); // NOI18N
        jButton1busca.setText("Buscar");
        jButton1busca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1buscaActionPerformed(evt);
            }
        });

        jLabel3nomprod.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3nomprod.setText("Nombre del producto ");

        buscarprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarprodActionPerformed(evt);
            }
        });
        buscarprod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                buscarprodKeyTyped(evt);
            }
        });

        jButton2cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.jpg"))); // NOI18N
        jButton2cancelar.setText("Cancelar");
        jButton2cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2cancelarActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inventario.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel3nomprod)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buscarprod)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel2)
                                .addGap(0, 115, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jButton1busca)
                        .addGap(68, 68, 68)
                        .addComponent(jButton2cancelar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(235, 235, 235))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3nomprod)
                    .addComponent(buscarprod, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1busca, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2cancelar))
                .addGap(35, 35, 35))
        );

        jTabbedPane1.addTab("Consultar ", jPanel2);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        datosventa.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        datosventa.setText("Datos de la venta ");

        jLabel5cliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5cliente.setText("Nombre del cliente: ");

        clientevendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientevendidoActionPerformed(evt);
            }
        });
        clientevendido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                clientevendidoKeyTyped(evt);
            }
        });

        jLabel6fecha.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6fecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6fecha.setText("Fecha");

        fechavendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechavendidoActionPerformed(evt);
            }
        });
        fechavendido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fechavendidoKeyTyped(evt);
            }
        });

        jTable1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cajero"));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "nombre", "fecha", "producto", "cantidad", "precio unitario", "total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel7total.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7total.setText("Total");

        jLabel8preciounitariop.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8preciounitariop.setText("Precio Unitario:");

        jLabel9cantidad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9cantidad.setText("Cantidad");

        preciounitario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preciounitarioActionPerformed(evt);
            }
        });
        preciounitario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                preciounitarioKeyTyped(evt);
            }
        });

        totalvendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalvendidoActionPerformed(evt);
            }
        });
        totalvendido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                totalvendidoKeyTyped(evt);
            }
        });

        btnnueva.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnnueva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.jpg"))); // NOI18N
        btnnueva.setText("Nueva");
        btnnueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevaActionPerformed(evt);
            }
        });

        btngenerarventa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btngenerarventa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/generarventa.jpg"))); // NOI18N
        btngenerarventa.setText("Generar Venta");
        btngenerarventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngenerarventaActionPerformed(evt);
            }
        });

        btnrecibo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnrecibo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/recibo.jpg"))); // NOI18N
        btnrecibo.setText("Recibo");
        btnrecibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreciboActionPerformed(evt);
            }
        });

        cancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.jpg"))); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        cantidadvendido.setModel(new javax.swing.SpinnerNumberModel(1, 1, 500, 1));

        prodvendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodvendidoActionPerformed(evt);
            }
        });
        prodvendido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                prodvendidoKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Producto: ");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/accept.png"))); // NOI18N
        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fechavendido, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clientevendido, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(prodvendido, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(datosventa))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(130, 130, 130)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel9cantidad)
                                                .addGap(44, 44, 44)
                                                .addComponent(cantidadvendido))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel8preciounitariop)
                                                    .addComponent(jLabel7total, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(totalvendido)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(preciounitario, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(0, 2, Short.MAX_VALUE))))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btngenerarventa)
                                .addGap(18, 18, 18)
                                .addComponent(btnrecibo)
                                .addGap(46, 46, 46)
                                .addComponent(btnnueva)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancelar)
                                .addGap(6, 6, 6)))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(25, 25, 25))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6fecha))
                        .addGap(550, 689, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5cliente)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(datosventa)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel9cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5cliente)
                            .addComponent(clientevendido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6fecha)
                            .addComponent(fechavendido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cantidadvendido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(prodvendido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8preciounitariop)
                                    .addComponent(preciounitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(totalvendido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7total)))))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnrecibo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btngenerarventa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(btnnueva, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("Realizar venta", jPanel1);

        jLabel1cajero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1cajero.setText("Cajero");

        jButton8salir.setText("Salir");
        jButton8salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1cajero, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(250, 250, 250)
                        .addComponent(jButton8salir, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8salir)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1cajero)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buscarprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarprodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarprodActionPerformed

    private void jButton8salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8salirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jButton8salirActionPerformed

    private void jButton1buscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1buscaActionPerformed
       buscarproducto();
    }//GEN-LAST:event_jButton1buscaActionPerformed
 public void buscarproducto(){
     String buscar=buscarprod.getText();
     String query="SELECT * FROM productos where nombre LIKE '%"+buscar+"%';";//buscar un producto donde el nombre sea 
     System.out.println(query);
      LimpiaTabla(); //limpiar la tabla 
      Object[] ob = new Object[7];
      try{
          conectandobd();// conectarse a lña base de datos 
          s= conexion.createStatement();// se crea un canal de comunicacion 
          ResultSet rs=s.executeQuery(query);
          int cont=1;

           while(rs.next()){
               ob[0] = rs.getObject("id");
               ob[1] = rs.getObject("nombre");
               ob[2] = rs.getObject("codigo");
               ob[3] = rs.getObject("precio");
               ob[4] = rs.getObject("categoria");
               ob[5] = rs.getObject("proovedor");
               ob[6] = rs.getObject("cantidad");
               tablaprod.addRow(ob);//agregar los obbjetos a la tabla productos 
               cont++;
           }
            
        }catch (Exception e) {
                System.err.println("El producto no existe");
            }
          //  jTable2.setModel(tabla);
 }
 public  void LimpiaTabla(){
     int a=tablaprod.getRowCount();    
     while(a!=0){ // Ciclo para Borrar la Tabla 1
         if(a!=0)
             tablaprod.removeRow(0);                      
         a=tablaprod.getRowCount();        
     }          
 }
    private void jButton2cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2cancelarActionPerformed
        JLabel x = new JLabel("Confirma que desea cancelarr" );
            Object[] x1={"",x};
                int si = JOptionPane.showConfirmDialog(null,x1,"Sistema de ventas",JOptionPane.OK_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);//preguntamos al usuario si esta confirmando el eliminar
                if(si==JOptionPane.OK_OPTION){
                buscarprod.setText("");
                }   

         
    }//GEN-LAST:event_jButton2cancelarActionPerformed

    private void btngenerarventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngenerarventaActionPerformed
        realizarventa();
        muestraventa();
     //   JOptionPane.showMessageDialog(null, "VENTA REALIZADA CON EXITO");
    }//GEN-LAST:event_btngenerarventaActionPerformed

    private void btnreciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreciboActionPerformed
  JOptionPane.showMessageDialog(null, "Generando su recibo");

    }//GEN-LAST:event_btnreciboActionPerformed

    private void btnnuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevaActionPerformed
//        System.out.println("Producto guardado en el inventario exitosamente ");
    realizarventa();
    }//GEN-LAST:event_btnnuevaActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
       	JLabel x = new JLabel("Confirma que desea cancelarr" );
            Object[] x1={"",x};
                int si = JOptionPane.showConfirmDialog(null,x1,"Sistema de ventas",JOptionPane.OK_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);//preguntamos al usuario si esta confirmando el eliminar
                if(si==JOptionPane.OK_OPTION){
                 clientevendido.setText("");
                 fechavendido.setText("");
                 prodvendido.setText("");
       
                preciounitario.setText("");
                totalvendido.setText("");
                }       	
    }//GEN-LAST:event_cancelarActionPerformed

    private void prodvendidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodvendidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodvendidoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       //limpiar las cajas de texto
        clientevendido.setText("");
        fechavendido.setText("");
        prodvendido.setText("");
       // cantidadvendido.setText("");
        preciounitario.setText("");
        totalvendido.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buscarprodKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarprodKeyTyped
   //permitir que solo se ingresen letras 
        char c=evt.getKeyChar();
        if(Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se permiten letras, no puede ingresar un numero !");

        }
    }//GEN-LAST:event_buscarprodKeyTyped

    private void clientevendidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clientevendidoKeyTyped
   //perimiti el ingreso de letras 
        char c=evt.getKeyChar();
        if(Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se permiten letras, no puede ingresar un numero !");

        }
    }//GEN-LAST:event_clientevendidoKeyTyped

    private void fechavendidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechavendidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechavendidoActionPerformed

  
    private void prodvendidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prodvendidoKeyTyped
       char c=evt.getKeyChar();
        if(Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se permiten letras, no puede ingresar un numero !");

        }
    }//GEN-LAST:event_prodvendidoKeyTyped

    private void preciounitarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preciounitarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_preciounitarioActionPerformed

    private void preciounitarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_preciounitarioKeyTyped
        char c=evt.getKeyChar();
        if(Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
             JOptionPane.showMessageDialog(null, "Solo se permiten numeros !");
        }
    }//GEN-LAST:event_preciounitarioKeyTyped

    private void totalvendidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalvendidoKeyTyped
     char c=evt.getKeyChar();
        if(Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
             JOptionPane.showMessageDialog(null, "Solo se permiten numeros !");
        }
    }//GEN-LAST:event_totalvendidoKeyTyped

    private void totalvendidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalvendidoActionPerformed

      Integer cantidad = (Integer)cantidadvendido.getValue();
      double value = Double.parseDouble(preciounitario.getText());
     int total= (int) (value*cantidad);
      totalvendido.setText(String.valueOf(total));
    }//GEN-LAST:event_totalvendidoActionPerformed

    private void fechavendidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fechavendidoKeyTyped
 //verificar que solo se ingrese numeros 
        char c=evt.getKeyChar();
        if(Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
             JOptionPane.showMessageDialog(null, "Solo se permiten numeros !","SISTEMA VENTAS",0);
        }    }//GEN-LAST:event_fechavendidoKeyTyped

    private void clientevendidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientevendidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientevendidoActionPerformed
public void realizarventa(){
    String nombreC=clientevendido.getText();
    String fechaV=fechavendido.getText();
    String prodV= prodvendido.getText();
    Integer cantidad= (Integer)cantidadvendido.getValue();
    //integer a string 
    String cantV= String.valueOf(cantidad);

    String precioU= preciounitario.getText();
    String Total= totalvendido.getText();
  
    try{
       
         conectandobd();
          int x=-1;
         String sql="insert into Venta (nombre,fecha,producto,cantidad,preciounitario,total) values (?,?,?,?,?,?);";
         ps= conexion.prepareStatement(sql);
         ps.setString(1, nombreC);
         ps.setString(2,fechaV );
         ps.setString(3,prodV );
         ps.setString(4,cantV);
         ps.setString(5,precioU);
         ps.setString(6,Total);
         x=ps.executeUpdate();
         System.out.println(ps.toString()); 
          if (x==-1){
                       JOptionPane.showMessageDialog(null, "Error: La venta del producto: "+prodvendido.getText()+" no se pudo realizar   ");
                   }else{
                       JOptionPane.showMessageDialog(null, "El Producto "+prodvendido.getText()+" se hizo correctamente!");
                    }
    }catch(Exception ex) {
        System.out.println(ex.getMessage());
 }
     muestraventa();
 }

  public void muestraventa(){//muestras  la venta 
    LimpiaTablaVenta(); //lipiar la tabla venta 
      Object[] ob = new Object[7];// array de objetos 
      try{
          conectandobd();//conectar a la base de datos 
           Statement s= conexion.createStatement();
           ResultSet rs=s.executeQuery("Select * from Venta");
           int cont=1;
  //         nombre,fecha,producto,cantidad,preciounitario,total
           while(rs.next()){
               ob[0] = cont;
               ob[1] = rs.getObject("nombre");
               ob[2] = rs.getObject("fecha");
               ob[3] = rs.getObject("producto");
               ob[4] = rs.getObject("cantidad");
               ob[5] = rs.getObject("preciounitario");
               ob[6] = rs.getObject("total");
               tablaventa.addRow(ob);
               cont++;
           }
        
        }catch (Exception e) {
               System.out.println(e.getMessage());
            //    System.err.println("Error al cargar usuarios");
            }
            jTable1.setModel(tablaventa);
            
  } public  void LimpiaTablaVenta(){
     int a=tablaventa.getRowCount();    
     while(a!=0){ // Ciclo para Borrar la Tabla 1
         if(a!=0)
             tablaventa.removeRow(0);                      
         a=tablaventa.getRowCount();        
     }          
 }
public void conectandobd(){
        try{
             //Se registra el driver
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            conexion= DriverManager.getConnection(url,us,pasword);
            System.out.println("conexión establecida en la clase cajero");
            }catch(Exception e){
              System.out.println(e.getMessage());
             System.out.println("error de conexion el el metodo conectar baser  de datos en cajero");
         }  
       }//fin del metodo conectando
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btngenerarventa;
    private javax.swing.JButton btnnueva;
    private javax.swing.JButton btnrecibo;
    private javax.swing.JTextField buscarprod;
    private javax.swing.JButton cancelar;
    private javax.swing.JSpinner cantidadvendido;
    private javax.swing.JTextField clientevendido;
    private javax.swing.JLabel datosventa;
    private javax.swing.JTextField fechavendido;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1busca;
    private javax.swing.JButton jButton2cancelar;
    private javax.swing.JButton jButton8salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1cajero;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3nomprod;
    private javax.swing.JLabel jLabel5cliente;
    private javax.swing.JLabel jLabel6fecha;
    private javax.swing.JLabel jLabel7total;
    private javax.swing.JLabel jLabel8preciounitariop;
    private javax.swing.JLabel jLabel9cantidad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField preciounitario;
    private javax.swing.JTextField prodvendido;
    private javax.swing.JTextField totalvendido;
    // End of variables declaration//GEN-END:variables
}
